baseurl: "https://lsudatasci.github.io/"
title: "Geaux code!"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Geaux code"
  Description: "codeFests and makerSpaces @LSU"
  Venue: "Life Sciences Building"
  Address: "Life Sciences Annex, Louisiana State University, 386 S Campus Dr."
  City:  "Baton Rouge"
  State: "LA, 70802"
  Images: ["/img/badge.jpg"]
#  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - schedule
    - partners

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    schedule: "Schedule"
    partners: "Partners"


  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register"
    link: "https://github.com/LSUdataSci/LSUdataSci.github.io/issues"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #  ForkButton:
  #    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Partners
  Partners:
    - name: "Louisiana State University"
      logo: "https://www.lsu.edu/science/your_question_next/images/logos/maincollege_vertical.png"
      url: "https://www.lsu.edu/science/"


  # The entire schedule
  Schedule:
    - name: ""
      time: ""
      presentation:
        time: "September 3 @ 5pm-7pm"
        title: "codeFest in the Life Sciences Building annex"
        description: "This month we will explore host-virus interaction data compiled by the Verena consortium, a collection of early-career virologists, ecologists, computational scientists, and policy experts."

    - name: ""
      time: ""
      presentation:
        time: "October 1 @ 5pm-7pm"
        title: "makerSpace in the Life Sciences Building annex"
        description: "This month we will make some neat things"


    - name: ""
      time: ""
      presentation:
        time: "November 5 @ 5pm-7pm"
        title: "codeFest in the Life Sciences Building annex"
        description: "This month we will explore some long-term monitoring data to explore, visualize, and analyze spatial and temporal patterns of ecological communities as part of NEON, the National Ecological Observatory Network"


    - name: ""
      time: ""
      presentation:
        time: "December 5 @ 5pm-7pm"
        title: "makerSpace in the Life Sciences Building annex"
        description: "This month we will make some neat things. Maybe something with LEDs for the holidays?"

    - name: ""
      time: ""
      presentation:
        time: "February 4 @ 5pm-7pm"
        title: "codeFest in the Life Sciences Building annex"
        description: "This month we will make some neat things. Maybe some generative art?"

    - name: ""
      time: ""
      presentation:
        time: "March 4 @ 5pm-7pm"
        title: "makerSpace in the Life Sciences Building annex"
        description: "This month we will make some neat things."

