baseurl: "https://example.org/"
title: "Geaux code!"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Geaux code"
  Description: "codeFests and makerSpaces @LSU"
  Date: ""
  Venue: "Life Sciences Building"
  Address: "Louisiana State University"
  City:  "Baton Rouge"
  State: "LA"
  Images: ["/img/badge.jpg"]
#  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - schedule
    - partners
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    schedule: "Schedule"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register"
    link: "https://github.com/LSUdataSci/LSUdataSci.github.io/issues"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #  ForkButton:
  #    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Partners
  Partners:
    - name: "Louisiana State University"
      logo: "https://www.lsu.edu/science/your_question_next/images/logos/maincollege_vertical.png"
      url: "https://www.lsu.edu/science/"


  # The entire schedule
  Schedule:
    - name: "September 3"
      time: "17h00"
      company: "codeFest"
      bio: "This month we will explore host-virus interaction data compiled by the Verena consortium, a collection of early-career virologists, ecologists, computational scientists, and policy experts."
      link: 
        href: https://github.com/LSUdataSci/LSUdataSci.github.io/issues
        text: "register here"

    - name: "October 1"
      time: "17h00"
      company: "makerSpace"
      bio: "This month we will make some neat things"
      link: 
        href: https://github.com/LSUdataSci/LSUdataSci.github.io/issues
        text: "register here"

    - name: "November 5"
      time: "17h00"
      company: "codeFest"
      bio: "This month we will explore some long-term monitoring data to explore, visualize, and analyze spatial and temporal patterns of ecological communities as part of NEON, the National Ecological Observatory Network"
      link: 
        href: https://github.com/LSUdataSci/LSUdataSci.github.io/issues
        text: "register here"
        
    - name: "December 3"
      time: "17h00"
      company: "makerSpace"
      bio: "This month we will make some neat things. Maybe something with LEDs for the holidays?"
      link: 
        href: https://github.com/LSUdataSci/LSUdataSci.github.io/issues
        text: "register here"

    - name: "February 4"
      time: "17h00"
      company: "codeFest"
      bio: "This month we will make some neat things"
      link: 
        href: https://github.com/LSUdataSci/LSUdataSci.github.io/issues
        text: "register here"    

    - name: "March 4"
      time: "17h00"
      company: "makerSpace"
      bio: "This month we will make some neat things."
      link: 
        href: https://github.com/LSUdataSci/LSUdataSci.github.io/issues
        text: "register here"
