baseurl: "https://lsudatasci.github.io/"
title: "Geaux code!"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "Geaux code"
  Description: "codeFests and makerSpaces @LSU"
  Venue: "Life Sciences Building"
  Address: "Life Sciences Annex, Louisiana State University, 386 S Campus Dr."
  City:  "Baton Rouge"
  State: "LA, 70802"
  Images: ["/img/geaux.png"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - schedule
    - partners

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    schedule: "Schedule"
    partners: "Partners"


  CallToAction:
    text: "Click here to register for the next makerSpace or codeFest!"
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfyQHnjg38zJ-5kbG_lpZjXCy0A0pKEplrtlF8Dnwi3_QDQSQ/viewform?usp=sf_link"

  # List of Partners
  Partners:
    - name: "Louisiana State University"
      logo: "https://www.lsu.edu/science/your_question_next/images/logos/maincollege_vertical.png"
      url: "https://www.lsu.edu/science/"

    - name: "Louisiana State University"
      logo: "https://pbs.twimg.com/profile_images/1027932669475094529/doKFCPLQ_400x400.jpg"
      url: "https://www.lsu.edu/science/biosci/"

    - name: "Dallas lab"
      logo: "/img/tShirt.png"
      url: "https://taddallas.github.io"


  # The entire schedule
  Schedule:
    - name: ""
      time: ""
      presentation:
        time: "September 3 @ 5pm-8pm"
        title: "POSTPONED DUE TO HURRICANE"
        description: "This month we will explore host-virus interaction data compiled by the Verena consortium, a collection of early-career virologists, ecologists, computational scientists, and policy experts."
        company: "https://github.com/LSUdataSci/verenaCodeFest"

    - name: ""
      time: ""
      presentation:
        time: "October 1 @ 5pm-8pm"
        title: "codeFest in the Life Sciences Building annex"
        description: "This month we will explore host-virus interaction data compiled by the Verena consortium, a collection of early-career virologists, ecologists, computational scientists, and policy experts."
        company: "https://github.com/LSUdataSci/verenaCodeFest"


    - name: ""
      time: ""
      presentation:
        time: "November 5 @ 5pm-8pm"
        title: "makerSpace in the Life Sciences Building annex"
        description: "This month we will make some neat things."
        company: "https://github.com/LSUdataSci/makerSpace"


    - name: ""
      time: ""
      presentation:
        time: "December 5 @ 5pm-8pm"
        title: "codeFest in the Life Sciences Building annex"
        description: "This month we will explore some long-term monitoring data to explore, visualize, and analyze spatial and temporal patterns of ecological communities as part of NEON, the National Ecological Observatory Network"
        company: "https://github.com/LSUdataSci/neonCodeFest"

    - name: ""
      time: ""
      presentation:
        time: "February 4 @ 5pm-8pm"
        title: "makerSpace in the Life Sciences Building annex"
        description: "This month we will make some neat things."
        company: "https://github.com/LSUdataSci/makerSpace"
     
    - name: ""
      time: ""
      presentation:
        time: "March 4 @ 5pm-8pm"
        title: "codeFest in the Life Sciences Building annex"
        description: "This month we will make some neat things. Maybe some generative art?"
        company: "https://github.com/LSUdataSci/"
        

